
{% set rdir = "../.." %}
{% set data = load_setup_py_data(setup_file=''+rdir+'/setup.py', from_recipe_dir=True) %}

package:
  name: biroamer
  version: {{ data.get('version') }}

source:
  - path: {{ rdir }}

build:
  string: "py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_DESCRIBE_HASH') }}"
  preserve_egg_dir: True

requirements:
  build:
    - make
    - cmake
    - gcc_linux-64
    - gxx_linux-64
  host:
    - pip
    - setuptools
    - python {{ python }}
    - gperftools
    - google-sparsehash
  run:
    - python {{ python }}
    - gperftools
    - google-sparsehash

about:
  home: https://github.com/bitextor/biroamer
  license: GPL3
  summary: Utility that will help you to ROAM (Random Omit Anonymize and Mix) your parallel corpus
